// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgqlfnovhwaqzhcllayz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndncWxmbm92aHdhcXpoY2xsYXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTY1NTUsImV4cCI6MjA2NzI5MjU1NX0.Lu-HVbW9fLN49tcLZThRlkZkb9V35pDtkrFO8tiCQEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});